spring.application.name=StudentMicroservice

spring.web.error.whitelabel.enabled=false
spring.h2.console.enabled=true

spring.datasource.url= jdbc:h2:file:./testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform= org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.default-zone = http://localhost:8761/eureka/
server.port=2222